[project]
name               = "PowerGrid"
version            = "2.0.0"
git_repo_url       = "https://github.com/acerjanic/PowerGrid/"
git_default_branch = "feature/metal-compute"

[paths]
compile_commands = "build/compile_commands.json"
output_dir       = "docs/api"

[ignore]
ignore_private_members = true
paths = [
  "PowerGrid/Tests/",
  "PowerGrid/Tutorials/",
  "PowerGrid/Microbenchmarks/",
  "Support/",
  "apps/",
]

[pages]
homepage = "docs/pages/index.md"
paths    = ["docs/pages/index.md"]
